import { z } from "zod";

export type User = { id: string; username: string; password: string; email: string; fullName: string | null; role: string; avatar: string | null; verified: boolean | null; blocked: boolean | null; verificationToken: string | null; createdAt: Date | null };
export type Campaign = { id: string; title: string; description: string; image: string; category: string; goalAmount: string; raisedAmount: string | null; startDate: Date | null; endDate: Date; status: string; urgent: boolean | null; location: string | null; archived: boolean | null; createdAt: Date | null };
export type Donation = { id: string; campaignId: string; donorId: string | null; amount: string; anonymous: boolean | null; message: string | null; paymentMethod: string; transactionId: string | null; createdAt: Date | null };
export type Story = { id: string; title: string; content: string; image: string | null; author: { name: string; role: string; avatar?: string } | null; authorId: string | null; campaignId: string | null; published: boolean | null; createdAt: Date | null };
export type Volunteer = { id: string; userId: string | null; campaignId: string | null; skills: string[] | null; availability: string | null; experience: string | null; status: string; createdAt: Date | null };
export type AidRequest = { id: string; userId: string; title: string; description: string; category: string; urgency: string; status: string; documents: string[] | null; location: string | null; createdAt: Date | null; updatedAt: Date | null };
export type InsertUser = { username: string; password: string; email: string; fullName?: string | null; role?: string; avatar?: string | null };
export type InsertCampaign = { title: string; description: string; image: string; category: string; goalAmount: string; startDate?: Date | null; endDate: Date; status?: string; urgent?: boolean | null; location?: string | null; archived?: boolean | null };
export type InsertDonation = { campaignId: string; donorId?: string | null; amount: string; anonymous?: boolean; message?: string | null; paymentMethod: string; transactionId?: string | null };
export type InsertStory = { title: string; content: string; image?: string | null; author?: Story["author"]; authorId?: string | null; campaignId?: string | null; published?: boolean };
export type InsertVolunteer = { userId?: string | null; campaignId?: string | null; skills?: string[] | null; availability?: string | null; experience?: string | null; status?: string };
export type InsertAidRequest = Omit<AidRequest, "id" | "createdAt" | "updatedAt" | "status">;

export const insertUserSchema = z.object({ username: z.string().min(1), password: z.string().min(1), email: z.string().email(), fullName: z.string().optional().nullable().default(""), role: z.string().optional().default("donor"), avatar: z.string().optional().nullable().default(null) });
export const insertCampaignSchema = z.object({ title: z.string(), description: z.string(), image: z.string(), category: z.string(), goalAmount: z.coerce.string(), startDate: z.coerce.date().optional(), endDate: z.coerce.date(), status: z.string().optional(), urgent: z.boolean().optional(), location: z.string().nullable().optional(), archived: z.boolean().optional() });
export const insertDonationSchema = z.object({ campaignId: z.string(), donorId: z.string().nullable().optional(), amount: z.coerce.string(), anonymous: z.boolean().optional(), message: z.string().nullable().optional(), paymentMethod: z.string(), transactionId: z.string().nullable().optional() });
export const insertStorySchema = z.object({ title: z.string(), content: z.string(), image: z.string().nullable().optional(), author: z.object({ name: z.string(), role: z.string(), avatar: z.string().optional() }).nullable().optional(), authorId: z.string().nullable().optional(), campaignId: z.string().nullable().optional(), published: z.boolean().optional() });
export const insertVolunteerSchema = z.object({ userId: z.string().nullable().optional(), campaignId: z.string().nullable().optional(), skills: z.array(z.string()).nullable().optional(), availability: z.string().nullable().optional(), experience: z.string().nullable().optional(), status: z.string().optional() });
export const insertAidRequestSchema = z.object({ userId: z.string().min(1), title: z.string().min(1).max(255), description: z.string().min(10).max(5000), category: z.enum(["medical", "education", "food", "shelter", "emergency", "other"]), urgency: z.enum(["low", "medium", "high", "emergency"]).default("medium"), location: z.string().min(1).max(255), documents: z.array(z.string()).optional().default([]) });
